"""auto update

Revision ID: 02a07a98fcf4
Revises: 88bdfcf1af96
Create Date: 2026-04-02 14:39:19.329252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a07a98fcf4'
down_revision: Union[str, Sequence[str], None] = '88bdfcf1af96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crx_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carerix_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('employee_carerix_id', sa.Integer(), nullable=True),
    sa.Column('vacancy_carerix_id', sa.Integer(), nullable=True),
    sa.Column('company_carerix_id', sa.Integer(), nullable=True),
    sa.Column('match_carerix_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('hours_per_week', sa.Float(), nullable=True),
    sa.Column('days_per_week', sa.Integer(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('purchase_rate', sa.Float(), nullable=True),
    sa.Column('hourly_tariff_invoice', sa.Float(), nullable=True),
    sa.Column('hourly_wage_gross', sa.Float(), nullable=True),
    sa.Column('margin_amount', sa.Float(), nullable=True),
    sa.Column('margin_percentage', sa.Float(), nullable=True),
    sa.Column('margin_ok', sa.Boolean(), nullable=True),
    sa.Column('sales_factor', sa.Float(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('customer_reference', sa.String(), nullable=True),
    sa.Column('external_identifier', sa.String(), nullable=True),
    sa.Column('job_information', sa.String(), nullable=True),
    sa.Column('memo_general', sa.String(), nullable=True),
    sa.Column('memo_declaration', sa.String(), nullable=True),
    sa.Column('invoice_subject', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('status_display', sa.String(), nullable=True),
    sa.Column('status_indication_color', sa.String(), nullable=True),
    sa.Column('owner_display', sa.String(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('carerix_created_date', sa.String(), nullable=True),
    sa.Column('carerix_modified_date', sa.String(), nullable=True),
    sa.Column('raw_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crx_jobs_id'), 'crx_jobs', ['id'], unique=False)
    op.create_table('crx_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carerix_id', sa.Integer(), nullable=True),
    sa.Column('match_title', sa.String(), nullable=True),
    sa.Column('employee_carerix_id', sa.Integer(), nullable=True),
    sa.Column('vacancy_carerix_id', sa.Integer(), nullable=True),
    sa.Column('company_carerix_id', sa.Integer(), nullable=True),
    sa.Column('publication_carerix_id', sa.Integer(), nullable=True),
    sa.Column('status_display', sa.String(), nullable=True),
    sa.Column('status_indication_color', sa.String(), nullable=True),
    sa.Column('motivation', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('fit_gap', sa.String(), nullable=True),
    sa.Column('cv_summary', sa.String(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('agreed_salary', sa.String(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('purchase_rate', sa.Float(), nullable=True),
    sa.Column('invoice_rate', sa.Float(), nullable=True),
    sa.Column('wage_rate', sa.Float(), nullable=True),
    sa.Column('margin_amount', sa.Float(), nullable=True),
    sa.Column('margin_percentage', sa.Float(), nullable=True),
    sa.Column('margin_ok', sa.Boolean(), nullable=True),
    sa.Column('sales_factor', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('source_info', sa.String(), nullable=True),
    sa.Column('apply_source', sa.String(), nullable=True),
    sa.Column('apply_medium', sa.String(), nullable=True),
    sa.Column('apply_campaign', sa.String(), nullable=True),
    sa.Column('apply_content', sa.String(), nullable=True),
    sa.Column('apply_term', sa.String(), nullable=True),
    sa.Column('job_start_date', sa.String(), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=True),
    sa.Column('owner_display', sa.String(), nullable=True),
    sa.Column('owner_carerix_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('carerix_created_date', sa.String(), nullable=True),
    sa.Column('carerix_modified_date', sa.String(), nullable=True),
    sa.Column('raw_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crx_matches_id'), 'crx_matches', ['id'], unique=False)
    op.create_table('crx_publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carerix_id', sa.Integer(), nullable=True),
    sa.Column('vacancy_carerix_id', sa.Integer(), nullable=True),
    sa.Column('company_carerix_id', sa.Integer(), nullable=True),
    sa.Column('title_information', sa.String(), nullable=True),
    sa.Column('title_information_html', sa.String(), nullable=True),
    sa.Column('intro_information', sa.String(), nullable=True),
    sa.Column('intro_information_html', sa.String(), nullable=True),
    sa.Column('vacancy_information', sa.String(), nullable=True),
    sa.Column('vacancy_information_html', sa.String(), nullable=True),
    sa.Column('requirements_information', sa.String(), nullable=True),
    sa.Column('requirements_information_html', sa.String(), nullable=True),
    sa.Column('offer_information', sa.String(), nullable=True),
    sa.Column('offer_information_html', sa.String(), nullable=True),
    sa.Column('company_information', sa.String(), nullable=True),
    sa.Column('company_information_html', sa.String(), nullable=True),
    sa.Column('application_contact_information', sa.String(), nullable=True),
    sa.Column('application_contact_information_html', sa.String(), nullable=True),
    sa.Column('function_contact_information', sa.String(), nullable=True),
    sa.Column('function_contact_information_html', sa.String(), nullable=True),
    sa.Column('work_location', sa.String(), nullable=True),
    sa.Column('work_location_html', sa.String(), nullable=True),
    sa.Column('vacancy_no', sa.String(), nullable=True),
    sa.Column('vacancy_url', sa.String(), nullable=True),
    sa.Column('apply_url', sa.String(), nullable=True),
    sa.Column('campaign', sa.String(), nullable=True),
    sa.Column('meta_tags', sa.String(), nullable=True),
    sa.Column('publication_start', sa.String(), nullable=True),
    sa.Column('publication_end', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('status_display', sa.String(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('owner_display', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('carerix_created_date', sa.String(), nullable=True),
    sa.Column('carerix_modified_date', sa.String(), nullable=True),
    sa.Column('raw_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crx_publications_id'), 'crx_publications', ['id'], unique=False)
    op.create_table('crx_todos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carerix_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('todo_name', sa.String(), nullable=True),
    sa.Column('todo_title', sa.String(), nullable=True),
    sa.Column('todo_type', sa.String(), nullable=True),
    sa.Column('todo_type_key', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('status_display', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=True),
    sa.Column('is_email', sa.Boolean(), nullable=True),
    sa.Column('is_meeting', sa.Boolean(), nullable=True),
    sa.Column('is_note', sa.Boolean(), nullable=True),
    sa.Column('is_task', sa.Boolean(), nullable=True),
    sa.Column('email_body', sa.String(), nullable=True),
    sa.Column('notes_text', sa.String(), nullable=True),
    sa.Column('from_address', sa.String(), nullable=True),
    sa.Column('to_address', sa.String(), nullable=True),
    sa.Column('cc_address', sa.String(), nullable=True),
    sa.Column('employee_carerix_id', sa.Integer(), nullable=True),
    sa.Column('vacancy_carerix_id', sa.Integer(), nullable=True),
    sa.Column('company_carerix_id', sa.Integer(), nullable=True),
    sa.Column('match_carerix_id', sa.Integer(), nullable=True),
    sa.Column('job_carerix_id', sa.Integer(), nullable=True),
    sa.Column('contact_carerix_id', sa.Integer(), nullable=True),
    sa.Column('owner_display', sa.String(), nullable=True),
    sa.Column('owner_carerix_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('carerix_created_date', sa.String(), nullable=True),
    sa.Column('carerix_modified_date', sa.String(), nullable=True),
    sa.Column('raw_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crx_todos_id'), 'crx_todos', ['id'], unique=False)
    op.create_table('sync_log_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('sync_type', sa.String(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_deleted', sa.Integer(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('filter_used', sa.String(), nullable=True),
    sa.Column('carerix_query_time_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_log_entries_id'), 'sync_log_entries', ['id'], unique=False)
    op.create_table('sync_metadata_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('last_sync_timestamp', sa.String(), nullable=True),
    sa.Column('last_full_sync', sa.String(), nullable=True),
    sa.Column('records_synced', sa.Integer(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_metadata_entries_id'), 'sync_metadata_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_metadata_entries_id'), table_name='sync_metadata_entries')
    op.drop_table('sync_metadata_entries')
    op.drop_index(op.f('ix_sync_log_entries_id'), table_name='sync_log_entries')
    op.drop_table('sync_log_entries')
    op.drop_index(op.f('ix_crx_todos_id'), table_name='crx_todos')
    op.drop_table('crx_todos')
    op.drop_index(op.f('ix_crx_publications_id'), table_name='crx_publications')
    op.drop_table('crx_publications')
    op.drop_index(op.f('ix_crx_matches_id'), table_name='crx_matches')
    op.drop_table('crx_matches')
    op.drop_index(op.f('ix_crx_jobs_id'), table_name='crx_jobs')
    op.drop_table('crx_jobs')
    # ### end Alembic commands ###