"""auto update

Revision ID: 2463f1bcab0b
Revises: 02a07a98fcf4
Create Date: 2026-04-02 22:40:32.896079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2463f1bcab0b'
down_revision: Union[str, Sequence[str], None] = '02a07a98fcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_metadata_entries', sa.Column('total_expected', sa.Integer(), nullable=True))
    op.add_column('sync_metadata_entries', sa.Column('current_fetched', sa.Integer(), nullable=True))
    op.add_column('sync_metadata_entries', sa.Column('current_upserted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_metadata_entries', 'current_upserted')
    op.drop_column('sync_metadata_entries', 'current_fetched')
    op.drop_column('sync_metadata_entries', 'total_expected')
    # ### end Alembic commands ###