"""auto update

Revision ID: 62c071464777
Revises: 2463f1bcab0b
Create Date: 2026-04-05 05:54:03.425605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c071464777'
down_revision: Union[str, Sequence[str], None] = '2463f1bcab0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_time', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.String(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('processed_at', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.drop_constraint(op.f('uq_companies_carerix_id'), 'companies', type_='unique')
    op.drop_constraint(op.f('uq_crx_jobs_carerix_id'), 'crx_jobs', type_='unique')
    op.drop_constraint(op.f('uq_crx_matches_carerix_id'), 'crx_matches', type_='unique')
    op.drop_constraint(op.f('uq_crx_publications_carerix_id'), 'crx_publications', type_='unique')
    op.drop_constraint(op.f('uq_crx_todos_carerix_id'), 'crx_todos', type_='unique')
    op.drop_constraint(op.f('uq_crx_vacancies_carerix_id'), 'crx_vacancies', type_='unique')
    op.drop_constraint(op.f('uq_employees_carerix_id'), 'employees', type_='unique')
    op.alter_column('sync_log_entries', 'records_skipped_unchanged',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_log_entries', 'records_skipped_unchanged',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_employees_carerix_id'), 'employees', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_crx_vacancies_carerix_id'), 'crx_vacancies', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_crx_todos_carerix_id'), 'crx_todos', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_crx_publications_carerix_id'), 'crx_publications', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_crx_matches_carerix_id'), 'crx_matches', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_crx_jobs_carerix_id'), 'crx_jobs', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_companies_carerix_id'), 'companies', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###