"""auto update

Revision ID: 6b552961af56
Revises: 62c071464777
Create Date: 2026-04-06 15:26:16.991834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b552961af56'
down_revision: Union[str, Sequence[str], None] = '62c071464777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('approval_stage', sa.String(), nullable=True),
    sa.Column('approver_role', sa.String(), nullable=True),
    sa.Column('approver_id', sa.String(), nullable=True),
    sa.Column('approver_name', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_actions_id'), 'approval_actions', ['id'], unique=False)
    op.create_table('correction_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('declaration_entry_id', sa.Integer(), nullable=True),
    sa.Column('payroll_period_id', sa.Integer(), nullable=True),
    sa.Column('placement_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('declaration_type_id', sa.Integer(), nullable=True),
    sa.Column('requested_amount', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('decline_reason', sa.String(), nullable=True),
    sa.Column('included_in_run', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('approved_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_requests_id'), 'correction_requests', ['id'], unique=False)
    op.create_table('declaration_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=True),
    sa.Column('placement_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('declaration_date', sa.String(), nullable=True),
    sa.Column('declaration_type_id', sa.Integer(), nullable=True),
    sa.Column('imported_amount', sa.Float(), nullable=True),
    sa.Column('applicable_fee', sa.Float(), nullable=True),
    sa.Column('calculated_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approval_stage', sa.String(), nullable=True),
    sa.Column('source_file_ref', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declaration_entries_id'), 'declaration_entries', ['id'], unique=False)
    op.create_table('declaration_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('finance_mapping', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declaration_types_id'), 'declaration_types', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_type', sa.String(), nullable=True),
    sa.Column('payroll_run_id', sa.Integer(), nullable=True),
    sa.Column('issuing_party', sa.String(), nullable=True),
    sa.Column('receiving_party', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('markup_amount', sa.Float(), nullable=True),
    sa.Column('markup_logic', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('issue_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('markup_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('percentage_value', sa.Float(), nullable=True),
    sa.Column('fixed_amount', sa.Float(), nullable=True),
    sa.Column('tier_definitions', sa.String(), nullable=True),
    sa.Column('valid_from', sa.String(), nullable=True),
    sa.Column('valid_to', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markup_configurations_id'), 'markup_configurations', ['id'], unique=False)
    op.create_table('payroll_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('finalized_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_periods_id'), 'payroll_periods', ['id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=True),
    sa.Column('correction_count', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('finalized_by', sa.String(), nullable=True),
    sa.Column('finalized_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_runs_id'), 'payroll_runs', ['id'], unique=False)
    op.create_table('platform_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_source', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('carerix_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('placement_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_users_id'), 'platform_users', ['id'], unique=False)
    op.drop_constraint(op.f('uq_companies_carerix_id'), 'companies', type_='unique')
    op.drop_constraint(op.f('uq_crx_jobs_carerix_id'), 'crx_jobs', type_='unique')
    op.drop_constraint(op.f('uq_crx_matches_carerix_id'), 'crx_matches', type_='unique')
    op.drop_constraint(op.f('uq_crx_publications_carerix_id'), 'crx_publications', type_='unique')
    op.drop_constraint(op.f('uq_crx_todos_carerix_id'), 'crx_todos', type_='unique')
    op.drop_constraint(op.f('uq_crx_vacancies_carerix_id'), 'crx_vacancies', type_='unique')
    op.drop_constraint(op.f('uq_employees_carerix_id'), 'employees', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_employees_carerix_id'), 'employees', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_crx_vacancies_carerix_id'), 'crx_vacancies', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_crx_todos_carerix_id'), 'crx_todos', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_crx_publications_carerix_id'), 'crx_publications', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_crx_matches_carerix_id'), 'crx_matches', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_crx_jobs_carerix_id'), 'crx_jobs', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_companies_carerix_id'), 'companies', ['carerix_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_platform_users_id'), table_name='platform_users')
    op.drop_table('platform_users')
    op.drop_index(op.f('ix_payroll_runs_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_payroll_periods_id'), table_name='payroll_periods')
    op.drop_table('payroll_periods')
    op.drop_index(op.f('ix_markup_configurations_id'), table_name='markup_configurations')
    op.drop_table('markup_configurations')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_declaration_types_id'), table_name='declaration_types')
    op.drop_table('declaration_types')
    op.drop_index(op.f('ix_declaration_entries_id'), table_name='declaration_entries')
    op.drop_table('declaration_entries')
    op.drop_index(op.f('ix_correction_requests_id'), table_name='correction_requests')
    op.drop_table('correction_requests')
    op.drop_index(op.f('ix_approval_actions_id'), table_name='approval_actions')
    op.drop_table('approval_actions')
    # ### end Alembic commands ###