"""auto update

Revision ID: 88bdfcf1af96
Revises: 2e79e7bbdfae
Create Date: 2026-04-02 14:38:27.374833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88bdfcf1af96'
down_revision: Union[str, Sequence[str], None] = '2e79e7bbdfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carerix_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('company_information', sa.String(), nullable=True),
    sa.Column('company_profile', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('fax_number', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('visit_address', sa.String(), nullable=True),
    sa.Column('visit_street', sa.String(), nullable=True),
    sa.Column('visit_number', sa.String(), nullable=True),
    sa.Column('visit_number_suffix', sa.String(), nullable=True),
    sa.Column('visit_postal_code', sa.String(), nullable=True),
    sa.Column('visit_city', sa.String(), nullable=True),
    sa.Column('visit_city_code', sa.String(), nullable=True),
    sa.Column('mailing_address', sa.String(), nullable=True),
    sa.Column('mailing_street', sa.String(), nullable=True),
    sa.Column('mailing_number', sa.String(), nullable=True),
    sa.Column('mailing_number_suffix', sa.String(), nullable=True),
    sa.Column('mailing_postal_code', sa.String(), nullable=True),
    sa.Column('mailing_city', sa.String(), nullable=True),
    sa.Column('mailing_city_code', sa.String(), nullable=True),
    sa.Column('invoice_address', sa.String(), nullable=True),
    sa.Column('invoice_city', sa.String(), nullable=True),
    sa.Column('invoice_postal_code', sa.String(), nullable=True),
    sa.Column('invoice_email_address', sa.String(), nullable=True),
    sa.Column('debtor_number', sa.String(), nullable=True),
    sa.Column('kvk_number', sa.String(), nullable=True),
    sa.Column('tax_number', sa.String(), nullable=True),
    sa.Column('company_size', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('fee_percentage', sa.Float(), nullable=True),
    sa.Column('branche_level1', sa.String(), nullable=True),
    sa.Column('branche_level2', sa.String(), nullable=True),
    sa.Column('status_display', sa.String(), nullable=True),
    sa.Column('status_indication_color', sa.String(), nullable=True),
    sa.Column('owner_display', sa.String(), nullable=True),
    sa.Column('owner_carerix_id', sa.Integer(), nullable=True),
    sa.Column('parent_carerix_id', sa.Integer(), nullable=True),
    sa.Column('source_info', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_competitor', sa.Boolean(), nullable=True),
    sa.Column('is_supplier', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('carerix_created_date', sa.String(), nullable=True),
    sa.Column('carerix_modified_date', sa.String(), nullable=True),
    sa.Column('raw_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('crx_vacancies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carerix_id', sa.Integer(), nullable=True),
    sa.Column('vacancy_no', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('title_information', sa.String(), nullable=True),
    sa.Column('intro_information', sa.String(), nullable=True),
    sa.Column('vacancy_information', sa.String(), nullable=True),
    sa.Column('offer_information', sa.String(), nullable=True),
    sa.Column('company_information', sa.String(), nullable=True),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('additional_information', sa.String(), nullable=True),
    sa.Column('contact_information', sa.String(), nullable=True),
    sa.Column('application_contact_information', sa.String(), nullable=True),
    sa.Column('training_information', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_carerix_id', sa.Integer(), nullable=True),
    sa.Column('work_location', sa.String(), nullable=True),
    sa.Column('work_city', sa.String(), nullable=True),
    sa.Column('work_city_code', sa.String(), nullable=True),
    sa.Column('work_postal_code', sa.String(), nullable=True),
    sa.Column('work_street', sa.String(), nullable=True),
    sa.Column('work_full_address', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('hours_per_week', sa.Float(), nullable=True),
    sa.Column('days_per_week', sa.Integer(), nullable=True),
    sa.Column('fte', sa.Float(), nullable=True),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('max_salary', sa.Float(), nullable=True),
    sa.Column('salary_scale', sa.String(), nullable=True),
    sa.Column('number_of_vacancies', sa.Integer(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('has_bonus', sa.Boolean(), nullable=True),
    sa.Column('has_company_car', sa.Boolean(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('active_publications_count', sa.Integer(), nullable=True),
    sa.Column('status_display', sa.String(), nullable=True),
    sa.Column('status_indication_color', sa.String(), nullable=True),
    sa.Column('owner_display', sa.String(), nullable=True),
    sa.Column('owner_carerix_id', sa.Integer(), nullable=True),
    sa.Column('source_info', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('customer_reference', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('carerix_created_date', sa.String(), nullable=True),
    sa.Column('carerix_modified_date', sa.String(), nullable=True),
    sa.Column('raw_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crx_vacancies_id'), 'crx_vacancies', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carerix_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('last_name_prefix', sa.String(), nullable=True),
    sa.Column('initials', sa.String(), nullable=True),
    sa.Column('full_first_names', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('email_address_business', sa.String(), nullable=True),
    sa.Column('email_address_private', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('phone_number_business', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('mobile_number_business', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('house_number', sa.String(), nullable=True),
    sa.Column('house_number_suffix', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('city_code', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('birth_city', sa.String(), nullable=True),
    sa.Column('gender_node', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('cv_summary', sa.String(), nullable=True),
    sa.Column('employee_information', sa.String(), nullable=True),
    sa.Column('experience_information', sa.String(), nullable=True),
    sa.Column('education_information', sa.String(), nullable=True),
    sa.Column('ambition', sa.String(), nullable=True),
    sa.Column('hobbies', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('skill_notes', sa.String(), nullable=True),
    sa.Column('language_notes', sa.String(), nullable=True),
    sa.Column('current_conditions', sa.String(), nullable=True),
    sa.Column('current_employer_name', sa.String(), nullable=True),
    sa.Column('current_salary', sa.Float(), nullable=True),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('available_date', sa.String(), nullable=True),
    sa.Column('available_from_date', sa.String(), nullable=True),
    sa.Column('hours_per_week', sa.Float(), nullable=True),
    sa.Column('days_per_week', sa.Integer(), nullable=True),
    sa.Column('fte', sa.Float(), nullable=True),
    sa.Column('min_fte', sa.Float(), nullable=True),
    sa.Column('max_fte', sa.Float(), nullable=True),
    sa.Column('max_distance', sa.Integer(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('has_car', sa.Boolean(), nullable=True),
    sa.Column('ranking', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('status_display', sa.String(), nullable=True),
    sa.Column('status_indication_color', sa.String(), nullable=True),
    sa.Column('owner_display', sa.String(), nullable=True),
    sa.Column('owner_carerix_id', sa.Integer(), nullable=True),
    sa.Column('source_info', sa.String(), nullable=True),
    sa.Column('active_job_count', sa.Integer(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('carerix_created_date', sa.String(), nullable=True),
    sa.Column('carerix_modified_date', sa.String(), nullable=True),
    sa.Column('raw_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_crx_vacancies_id'), table_name='crx_vacancies')
    op.drop_table('crx_vacancies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###