from core.database import Base
from sqlalchemy import Boolean, Column, Float, Integer, String


class Companies(Base):
    __tablename__ = "companies"
    __table_args__ = {"extend_existing": True}

    id = Column(Integer, primary_key=True, index=True, autoincrement=True, nullable=False)
    carerix_id = Column(Integer, nullable=True)
    name = Column(String, nullable=True)
    short_name = Column(String, nullable=True)
    division = Column(String, nullable=True)
    company_information = Column(String, nullable=True)
    company_profile = Column(String, nullable=True)
    email_address = Column(String, nullable=True)
    phone_number = Column(String, nullable=True)
    fax_number = Column(String, nullable=True)
    url = Column(String, nullable=True)
    linkedin_url = Column(String, nullable=True)
    visit_address = Column(String, nullable=True)
    visit_street = Column(String, nullable=True)
    visit_number = Column(String, nullable=True)
    visit_number_suffix = Column(String, nullable=True)
    visit_postal_code = Column(String, nullable=True)
    visit_city = Column(String, nullable=True)
    visit_city_code = Column(String, nullable=True)
    mailing_address = Column(String, nullable=True)
    mailing_street = Column(String, nullable=True)
    mailing_number = Column(String, nullable=True)
    mailing_number_suffix = Column(String, nullable=True)
    mailing_postal_code = Column(String, nullable=True)
    mailing_city = Column(String, nullable=True)
    mailing_city_code = Column(String, nullable=True)
    invoice_address = Column(String, nullable=True)
    invoice_city = Column(String, nullable=True)
    invoice_postal_code = Column(String, nullable=True)
    invoice_email_address = Column(String, nullable=True)
    debtor_number = Column(String, nullable=True)
    kvk_number = Column(String, nullable=True)
    tax_number = Column(String, nullable=True)
    company_size = Column(Integer, nullable=True)
    revenue = Column(Float, nullable=True)
    fee_percentage = Column(Float, nullable=True)
    branche_level1 = Column(String, nullable=True)
    branche_level2 = Column(String, nullable=True)
    status_display = Column(String, nullable=True)
    status_indication_color = Column(String, nullable=True)
    owner_display = Column(String, nullable=True)
    owner_carerix_id = Column(Integer, nullable=True)
    parent_carerix_id = Column(Integer, nullable=True)
    source_info = Column(String, nullable=True)
    notes = Column(String, nullable=True)
    is_competitor = Column(Boolean, nullable=True)
    is_supplier = Column(Boolean, nullable=True)
    deleted = Column(Boolean, nullable=True)
    carerix_created_date = Column(String, nullable=True)
    carerix_modified_date = Column(String, nullable=True)
    raw_json = Column(String, nullable=True)