from core.database import Base
from sqlalchemy import Boolean, Column, Float, Integer, String


class Crx_vacancies(Base):
    __tablename__ = "crx_vacancies"
    __table_args__ = {"extend_existing": True}

    id = Column(Integer, primary_key=True, index=True, autoincrement=True, nullable=False)
    carerix_id = Column(Integer, nullable=True)
    vacancy_no = Column(String, nullable=True)
    job_title = Column(String, nullable=True)
    title_information = Column(String, nullable=True)
    intro_information = Column(String, nullable=True)
    vacancy_information = Column(String, nullable=True)
    offer_information = Column(String, nullable=True)
    company_information = Column(String, nullable=True)
    requirements = Column(String, nullable=True)
    additional_information = Column(String, nullable=True)
    contact_information = Column(String, nullable=True)
    application_contact_information = Column(String, nullable=True)
    training_information = Column(String, nullable=True)
    company_name = Column(String, nullable=True)
    company_carerix_id = Column(Integer, nullable=True)
    work_location = Column(String, nullable=True)
    work_city = Column(String, nullable=True)
    work_city_code = Column(String, nullable=True)
    work_postal_code = Column(String, nullable=True)
    work_street = Column(String, nullable=True)
    work_full_address = Column(String, nullable=True)
    start_date = Column(String, nullable=True)
    end_date = Column(String, nullable=True)
    deadline = Column(String, nullable=True)
    hours_per_week = Column(Float, nullable=True)
    days_per_week = Column(Integer, nullable=True)
    fte = Column(Float, nullable=True)
    min_salary = Column(Float, nullable=True)
    max_salary = Column(Float, nullable=True)
    salary_scale = Column(String, nullable=True)
    number_of_vacancies = Column(Integer, nullable=True)
    is_anonymous = Column(Boolean, nullable=True)
    is_hidden = Column(Boolean, nullable=True)
    is_template = Column(Boolean, nullable=True)
    has_bonus = Column(Boolean, nullable=True)
    has_company_car = Column(Boolean, nullable=True)
    match_count = Column(Integer, nullable=True)
    active_publications_count = Column(Integer, nullable=True)
    status_display = Column(String, nullable=True)
    status_indication_color = Column(String, nullable=True)
    owner_display = Column(String, nullable=True)
    owner_carerix_id = Column(Integer, nullable=True)
    source_info = Column(String, nullable=True)
    notes = Column(String, nullable=True)
    customer_reference = Column(String, nullable=True)
    deleted = Column(Boolean, nullable=True)
    carerix_created_date = Column(String, nullable=True)
    carerix_modified_date = Column(String, nullable=True)
    raw_json = Column(String, nullable=True)