from core.database import Base
from sqlalchemy import Boolean, Column, Float, Integer, String


class Employees(Base):
    __tablename__ = "employees"
    __table_args__ = {"extend_existing": True}

    id = Column(Integer, primary_key=True, index=True, autoincrement=True, nullable=False)
    carerix_id = Column(Integer, nullable=True)
    first_name = Column(String, nullable=True)
    last_name = Column(String, nullable=True)
    last_name_prefix = Column(String, nullable=True)
    initials = Column(String, nullable=True)
    full_first_names = Column(String, nullable=True)
    name = Column(String, nullable=True)
    title = Column(String, nullable=True)
    email_address = Column(String, nullable=True)
    email_address_business = Column(String, nullable=True)
    email_address_private = Column(String, nullable=True)
    phone_number = Column(String, nullable=True)
    phone_number_business = Column(String, nullable=True)
    mobile_number = Column(String, nullable=True)
    mobile_number_business = Column(String, nullable=True)
    address = Column(String, nullable=True)
    street = Column(String, nullable=True)
    house_number = Column(String, nullable=True)
    house_number_suffix = Column(String, nullable=True)
    postal_code = Column(String, nullable=True)
    city = Column(String, nullable=True)
    city_code = Column(String, nullable=True)
    birth_date = Column(String, nullable=True)
    birth_city = Column(String, nullable=True)
    gender_node = Column(Integer, nullable=True)
    age = Column(Integer, nullable=True)
    cv_summary = Column(String, nullable=True)
    employee_information = Column(String, nullable=True)
    experience_information = Column(String, nullable=True)
    education_information = Column(String, nullable=True)
    ambition = Column(String, nullable=True)
    hobbies = Column(String, nullable=True)
    notes = Column(String, nullable=True)
    skill_notes = Column(String, nullable=True)
    language_notes = Column(String, nullable=True)
    current_conditions = Column(String, nullable=True)
    current_employer_name = Column(String, nullable=True)
    current_salary = Column(Float, nullable=True)
    min_salary = Column(Float, nullable=True)
    salary = Column(Integer, nullable=True)
    available_date = Column(String, nullable=True)
    available_from_date = Column(String, nullable=True)
    hours_per_week = Column(Float, nullable=True)
    days_per_week = Column(Integer, nullable=True)
    fte = Column(Float, nullable=True)
    min_fte = Column(Float, nullable=True)
    max_fte = Column(Float, nullable=True)
    max_distance = Column(Integer, nullable=True)
    years_of_experience = Column(Integer, nullable=True)
    has_car = Column(Boolean, nullable=True)
    ranking = Column(Float, nullable=True)
    rating = Column(Integer, nullable=True)
    engagement_score = Column(Integer, nullable=True)
    completeness_score = Column(Float, nullable=True)
    status_display = Column(String, nullable=True)
    status_indication_color = Column(String, nullable=True)
    owner_display = Column(String, nullable=True)
    owner_carerix_id = Column(Integer, nullable=True)
    source_info = Column(String, nullable=True)
    active_job_count = Column(Integer, nullable=True)
    match_count = Column(Integer, nullable=True)
    is_confidential = Column(Boolean, nullable=True)
    deleted = Column(Boolean, nullable=True)
    carerix_created_date = Column(String, nullable=True)
    carerix_modified_date = Column(String, nullable=True)
    raw_json = Column(String, nullable=True)